version: '3'
services:
  db:
    image: postgres:11
    ports:
      - "32700:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ggg
      POSTGRES_PASSWORD: dddd
      POSTGRES_DB: dbdb

